version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flaskBackend
    restart: always
    expose:
      - "5000"
    volumes:
      - ./backend:/app
      - model-data:/app/models
    environment:
      - FLASK_ENV=development
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend/chenapan
      dockerfile: Dockerfile
      no_cache: true
    container_name: reactFrontend
    restart: always
    ports:
      - "80:80"  # Map to standard HTTP port
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    name: chenapan-network
    driver: bridge

volumes:
  model-data:
    name: chenapan-model-data
