version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flaskBackend
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
    environment:
      - FLASK_ENV=development

  frontend:
     build: ./frontend/chenapan
     container_name: reactFrontend
     restart: always
     ports:
      - "80:80"
     depends_on:
      - backend
     env_file:
      - ./frontend/chenapan/.env
